### ISSUE TITLE
Implement an LSTM based prediction Model

### ISSUE THREAD

**Issue by parulc7** [Deathrow77/Alice-in-Wonderland#3]
The contributer should develop a LSTM based approach to achieve better prediction accuracy

**Comment by shreyateeza** [comment]
@Deathrow77  I want to work on this issue as a part of KWoC 2019.

**Comment by parulc7** [comment]
Go ahead @shreyateeza ... Please create a seperate folder for the same.

**Comment by youdit** [comment]
I have implemented the LSTM based prediction model.I request you to please have a look at it.
Accuracy achieved the training accuracy of 67%.

**Comment by shreyateeza** [comment]
@Deathrow77 @youdit has already created a PR for this issue. So can I still work on this for KWOC?

**Comment by parulc7** [comment]
If you can tweak your hyperparameters to give better results. I have still not merged the PR because I want the most optimized model from all the participants.

**Comment by milindthakur177** [comment]
@Deathrow77 I know it is a bit late but can i work on this issue?

**Comment by parulc7** [comment]
@milindthakur177 I have already merged a PR which leverages this model. If you want to, you can use a word2vec model for prediction
